apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guestbook-dev
resources:
- ../../base
patchesStrategicMerge:
- deployment-patch.yaml
images:
- name: sample-microservice
  newName: ghcr.io/your-username/sample-microservice
  newTag: dev-latest
